name: Update D-n Labels
on:
  schedule:
    - cron: '*/2 * * * *' # 1분마다 실행
jobs:
  d-day-labeler:
    runs-on: [ubuntu-latest]
    steps:
      - name: Update D-n Labels
        uses: naver/d-day-labeler@latest
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
