name: PR Review Slack Notifier

on:
  schedule:
    - cron: '10 4 * * 1-5' # 평일 오전 10시(KST) 실행 (UTC 기준 1시)

jobs:
  request_pr_review:
    runs-on: ubuntu-latest
    steps:
      - name: Request PR Review
        uses: naver/request-pr-review@v1.2.1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}
          repoUrl: 'https://github.com/jeongyunjae/pr-review-test'
