name: PR Review Slack Notifier

on:
  workflow_dispatch: # 수동 실행 가능
  schedule:
    - cron: '20 4 * * 1-5'

jobs:
  request_pr_review:
    runs-on: ubuntu-latest
    steps:
      - name: Request PR Review
        uses: naver/request-pr-review@v1.2.1
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}
          repoUrl: 'https://github.com/jeongyunjae/pr-review-test'
