name: PR Labeler

on:
  schedule:
    - cron: '20 2 * * *' # 매일 오전 11시 20분(KST) 실행 (UTC 기준 2시 20분)
      branches:
        - 'pr-review-test'
  pull_request:
    types: [opened]
    branches:
      - 'main'
jobs:
  Automatic-PR-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: JayKim88/automatic-pr-labeler@master
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
