name: PR Automation Workflow

on:
  pull_request:
    types: [opened, ready_for_review]
  schedule:
    - cron: '*/1 * * * *' # 1분마다 실행

jobs:
  # 1. PR 생성 시 D-n 라벨 자동 추가
  add_d_n_label:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'ready_for_review')
    runs-on: ubuntu-latest
    steps:
      - name: Add D-n Label to PR
        uses: naver/simple-labeler@latest
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          labels: 'D-3'
          duplicate: 'D-*'
