name: PR Automation Workflow

on:
  schedule:
    - cron: '*/1 * * * *' # 1분마다 실행

jobs:
  # 2. 매일 자정 D-n Label 업데이트 (D-n -> D-(n-1))
  update_d_n_label:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Update D-n Labels
        uses: naver/d-day-labeler@latest
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
