name: Update D-n Label

on:
  schedule:
    - cron: '12 4 * * 1-5' # 매일 자정(KST) 실행 (UTC 기준 15시)

jobs:
  update_d_n_label:
    runs-on: ubuntu-latest
    steps:
      - name: Update D-n Labels
        uses: naver/d-day-labeler@latest
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
