name: Update D-n Label

on:
  workflow_dispatch: # 수동 실행 가능
  schedule:
    - cron: '20 4 * * 1-5'

jobs:
  update_d_n_label:
    runs-on: ubuntu-latest
    steps:
      - name: Update D-n Labels
        uses: naver/d-day-labeler@latest
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
